import React, { useEffect, useState } from "react";

export default function ReportGenerator({ conversation }) {
  const [report, setReport] = useState("");

  useEffect(() => {
    if (conversation && conversation.length > 0) {
      const userMessages = conversation
        .filter((m) => m.role === "user")
        .map((m) => m.text);
      const botMessages = conversation
        .filter((m) => m.role === "bot")
        .map((m) => m.text);

      const summary = `
🩺 SwiftCare AI Health Report
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📅 Date & Time: ${new Date().toLocaleString()}

👤 Report Summary
----------------------------------
🧍 Symptoms Reported:
${userMessages.join("\n\n")}

🤖 AI Suggestions:
${botMessages.join("\n\n")}

💡 This report was auto-generated by SwiftCare AI Assistant to summarize the conversation.
      `;

      setReport(summary.trim());
    }
  }, [conversation]);

  if (!report) return null;

  // Download report handler
  const handleDownload = () => {
    const blob = new Blob([report], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `SwiftCare_Report_${new Date()
      .toISOString()
      .replace(/[:.]/g, "-")}.txt`;
    link.click();
  };

  return (
    <div className="rounded-3xl p-6 bg-white/10 backdrop-blur-xl border border-cyan-400/30 shadow-[0_0_25px_rgba(0,255,255,0.15)] mt-6 transition-all duration-300">
      <h3 className="text-lg font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-300 to-sky-400 mb-3 drop-shadow-[0_0_10px_#00ffff70]">
        🧾 AI-Generated Health Report
      </h3>

      {/* Report content */}
      <pre className="text-sm font-mono bg-[#0b132b]/70 text-cyan-100 p-4 rounded-2xl border border-white/10 whitespace-pre-wrap shadow-inner max-h-[300px] overflow-y-auto">
        {report}
      </pre>

      {/* Download Button */}
      <button
        onClick={handleDownload}
        className="mt-4 px-5 py-2.5 rounded-xl text-white font-semibold text-sm bg-gradient-to-r from-cyan-500 to-sky-500 hover:scale-105 hover:shadow-[0_0_20px_rgba(0,255,255,0.4)] transition-all"
      >
        ⬇️ Download Report
      </button>
    </div>
  );
}
